apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
    - name: liveness-container-test
      args:
        - /bin/sh
        - "-c"
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600

      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5 # Tempo de espera antes do primeiro teste
        periodSeconds: 5 # Frequência com que o teste é executado
        failureThreshold: 3 # Quantas falhas antes de reiniciar o Pod
