apiVersion: v1
kind: Service
matadata:
  name: svc-sts
spec:
  ports:
  - port: 80
  clusterIP: none
  selector:
    app: nginx-app-pods
---
apiVersion: appps/v1
kind: Statefulset
matadata:
  name: my-sts
spec:
  selector:
    matchLabels:
        app: nginx-app-pods

    serviceName: "svc-sts"
    replicas: 5
    template:
      metadata:
       labels:
           app: nginx-app-pods
      spec:
        containers:
         -name: my-container
         image: nginx
         volumesMounts:
         - name: my-pv
         mountPath: /usr/share/nginx/html
      volumeClaimTemplates:
      - metadata:
          name: my-pv
        spec:
          accessModes: ["RadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
