apiVersion: v1
kind: Service
metadata:
  name: svc-sts
spec:
  ports:
  - port: 80
  clusterIP: None
  selector:
    app: nginx-app-pods
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: my-sts
spec:
  selector:
    matchLabels:
      app: nginx-app-pods # Selector deve corresponder às labels do Pod
  serviceName: "svc-sts" # Liga o StatefulSet ao Headless Service acima
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx-app-pods
    spec:
      containers:
      - name: my-container
        image: nginx
        volumeMounts:
        - name: my-pv
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates: # Responsável por criar os PVCs automaticamente
  - metadata:
      name: my-pv
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi